repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=79]
        exclude: ^(venv/|backend/venv/|frontend-web/venv/|frontend-mobile/venv/|infra/venv/|\.venv/) 